---

spring:
  cloud:
    config:
      server:
        git:
          uri: ${vcap.services.myconfigrepo.credentials.repo}

security:
  user:
    name: cfguser
    password: cfgpass

eureka:
  client:
    serviceUrl:
      defaultZone: http://euruser:eurpass@eurekasvr-jcabuhat.cfapps.io/eureka

